import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="sticky top-0 z-50 flex items-center justify-between px-4 py-3">
          <div className="flex items-center">
            <Image
              src="/logo.svg"
              alt="Logo"
              width={120}
              height={40}
              className="w-35 h-auto"
            />
          </div>
          <Link href="/profile" className="text-gray-700 hover:text-black">
            <Image
              src="/user.svg"
              alt="User Icon"
              width={120}
              height={40}
              className="w-5 h-auto"
            />
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
