import type { Metadata } from "next";
import "./globals.css";
import PrimaryNavigation from "@/lib/components/primary-navigation";
import AudioPlayerComponent from "@/lib/components/audio-player";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {<PrimaryNavigation />}
        {children}
        <footer className="fixed bottom-0 left-0 w-full z-50">
          {<AudioPlayerComponent />}
        </footer>
      </body>
    </html>
  );
}
